services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: url_shortener
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - app-network
  web:
    image: shinsenter/symfony:latest
    restart: always
    container_name: web
    tty: true
    env_file:
      - .env
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    networks:
      - app-network

networks:
  app-network:
volumes:
  db_data: