services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: url_shortener
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-network

  php:
    build:
      context: ./api
    restart: always
    container_name: api
    tty: true
    environment:
      DATABASE_URL: mysql://root:password@db:3306/url_shortener?serverVersion=mariadb-10.11.3&charset=utf8mb4
    working_dir: /var/www/html
    command: >
      bash -c "composer update && php -S 0.0.0.0:9000 -t public"
    ports:
      - 9000:9000
    volumes:
      - ./api:/var/www/html
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9090:80
    environment:
      MYSQL_USERNAME: user
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - app-network

  node:
    build:
      context: ./web
    volumes:
      - ./web:/srv/app
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - app-network
      
networks:
  app-network:
volumes:
  db_data:
